/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.sava.avaliacaoindividual.view;

import br.com.ifba.sava.infrastructure.view.HomeScreen;

/**
 *
 * @author marts
 */
public class AvaliarIndividual extends javax.swing.JFrame {

    /**
     * Creates new form AvaliarIndividual
     */
    public AvaliarIndividual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainContainer2 = new javax.swing.JPanel();
        pnlRegisterContainer2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvalicaoIndividual = new javax.swing.JTable();
        btnVoltarAvalicaoIndividual = new javax.swing.JButton();
        btnAvaliarIndividual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainContainer2.setBackground(new java.awt.Color(72, 71, 97));

        pnlRegisterContainer2.setBackground(new java.awt.Color(218, 217, 237));
        pnlRegisterContainer2.setBorder(new javax.swing.border.MatteBorder(null));

        tblAvalicaoIndividual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reprovação", "Não Fez a Recuperação", "Frequência Baixa", "Não Participa", "Não Fez as Atividades", "Não Frequenta Atendimento", "Apresenta Conversa Paralela", "Usa Celular/Fone", "Não é Pontual", "Sai e Entra da Sala", "Dif. de Interpretação de Texto", "Dif. em Operações Matemáticas", "Dif. na Expressão Oral", "Dif. de Concentração", "Questões Emocionais", "Comentários Por Disciplina", "Comentários Gerais", "Diagnóstico", "Encaminhamento"
            }
        ));
        tblAvalicaoIndividual.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tblAvalicaoIndividual);
        tblAvalicaoIndividual.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout pnlRegisterContainer2Layout = new javax.swing.GroupLayout(pnlRegisterContainer2);
        pnlRegisterContainer2.setLayout(pnlRegisterContainer2Layout);
        pnlRegisterContainer2Layout.setHorizontalGroup(
            pnlRegisterContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRegisterContainer2Layout.setVerticalGroup(
            pnlRegisterContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnVoltarAvalicaoIndividual.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltarAvalicaoIndividual.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnVoltarAvalicaoIndividual.setText("voltar");
        btnVoltarAvalicaoIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAvalicaoIndividualActionPerformed(evt);
            }
        });

        btnAvaliarIndividual.setBackground(new java.awt.Color(72, 71, 97));
        btnAvaliarIndividual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAvaliarIndividual.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliarIndividual.setText("Avaliar");
        btnAvaliarIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarIndividualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainContainer2Layout = new javax.swing.GroupLayout(pnlMainContainer2);
        pnlMainContainer2.setLayout(pnlMainContainer2Layout);
        pnlMainContainer2Layout.setHorizontalGroup(
            pnlMainContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainer2Layout.createSequentialGroup()
                .addGroup(pnlMainContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainContainer2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlRegisterContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMainContainer2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnVoltarAvalicaoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainContainer2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAvaliarIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(533, 533, 533))
        );
        pnlMainContainer2Layout.setVerticalGroup(
            pnlMainContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainer2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnVoltarAvalicaoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(pnlRegisterContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAvaliarIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarAvalicaoIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAvalicaoIndividualActionPerformed
        this.dispose();
        HomeScreen tela1 = new HomeScreen();
        tela1.setVisible(true);
        
    }//GEN-LAST:event_btnVoltarAvalicaoIndividualActionPerformed

    private void btnAvaliarIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarIndividualActionPerformed

    }//GEN-LAST:event_btnAvaliarIndividualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliarIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliarIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliarIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliarIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaliarIndividual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliarIndividual;
    private javax.swing.JButton btnVoltarAvalicaoIndividual;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlMainContainer2;
    private javax.swing.JPanel pnlRegisterContainer2;
    private javax.swing.JTable tblAvalicaoIndividual;
    // End of variables declaration//GEN-END:variables
}
