/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.sava.disciplina.view;

import br.com.ifba.sava.disciplina.model.Disciplina;
import br.com.ifba.sava.infrastructure.service.FacadeInstance;

/**
 *
 * @author marts
 */
public class CadastrarDisciplina extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarDisciplina
     */
    public CadastrarDisciplina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlMainContainer = new javax.swing.JPanel();
        pnlRegisterContainer = new javax.swing.JPanel();
        pnlNomeDisciplina = new javax.swing.JPanel();
        lblNomeDisciplina = new javax.swing.JLabel();
        txtNomeDisciplina = new javax.swing.JTextField();
        pnlCodigoDisciplina = new javax.swing.JPanel();
        lblCodigoDisciplina = new javax.swing.JLabel();
        txtCodigoDisiciplina = new javax.swing.JTextField();
        btnCadastrarDisciplina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainContainer.setBackground(new java.awt.Color(72, 71, 97));

        pnlRegisterContainer.setBackground(new java.awt.Color(218, 217, 237));

        pnlNomeDisciplina.setBackground(new java.awt.Color(102, 101, 120));
        pnlNomeDisciplina.setPreferredSize(new java.awt.Dimension(254, 38));

        lblNomeDisciplina.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblNomeDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeDisciplina.setText("Nome:");

        txtNomeDisciplina.setBackground(new java.awt.Color(102, 101, 120));
        txtNomeDisciplina.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        txtNomeDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeDisciplina.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNomeDisciplina.setMinimumSize(new java.awt.Dimension(3, 17));

        javax.swing.GroupLayout pnlNomeDisciplinaLayout = new javax.swing.GroupLayout(pnlNomeDisciplina);
        pnlNomeDisciplina.setLayout(pnlNomeDisciplinaLayout);
        pnlNomeDisciplinaLayout.setHorizontalGroup(
            pnlNomeDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeDisciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(txtNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNomeDisciplinaLayout.setVerticalGroup(
            pnlNomeDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNomeDisciplinaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeDisciplina)
                .addContainerGap())
            .addComponent(txtNomeDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlCodigoDisciplina.setBackground(new java.awt.Color(102, 101, 120));
        pnlCodigoDisciplina.setPreferredSize(new java.awt.Dimension(254, 38));

        lblCodigoDisciplina.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblCodigoDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoDisciplina.setText("Código:");

        txtCodigoDisiciplina.setBackground(new java.awt.Color(102, 101, 120));
        txtCodigoDisiciplina.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        txtCodigoDisiciplina.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoDisiciplina.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout pnlCodigoDisciplinaLayout = new javax.swing.GroupLayout(pnlCodigoDisciplina);
        pnlCodigoDisciplina.setLayout(pnlCodigoDisciplinaLayout);
        pnlCodigoDisciplinaLayout.setHorizontalGroup(
            pnlCodigoDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigoDisciplina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoDisiciplina, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );
        pnlCodigoDisciplinaLayout.setVerticalGroup(
            pnlCodigoDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoDisciplinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigoDisciplina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(txtCodigoDisiciplina)
        );

        btnCadastrarDisciplina.setBackground(new java.awt.Color(72, 71, 97));
        btnCadastrarDisciplina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarDisciplina.setText("Cadastrar Disicplina");
        btnCadastrarDisciplina.setPreferredSize(new java.awt.Dimension(131, 23));
        btnCadastrarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterContainerLayout = new javax.swing.GroupLayout(pnlRegisterContainer);
        pnlRegisterContainer.setLayout(pnlRegisterContainerLayout);
        pnlRegisterContainerLayout.setHorizontalGroup(
            pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCodigoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        pnlRegisterContainerLayout.setVerticalGroup(
            pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(pnlNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCodigoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(btnCadastrarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout pnlMainContainerLayout = new javax.swing.GroupLayout(pnlMainContainer);
        pnlMainContainer.setLayout(pnlMainContainerLayout);
        pnlMainContainerLayout.setHorizontalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainerLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(pnlRegisterContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        pnlMainContainerLayout.setVerticalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainerLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(pnlRegisterContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void btnCadastrarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
        Disciplina disciplina1 = new Disciplina();
        
        disciplina1.setNome(txtNomeDisciplina.getText());
        disciplina1.setCodigo(txtCodigoDisiciplina.getText());
        
        
        FacadeInstance.getInstance().saveDisciplina(disciplina1);
    }                                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCadastrarDisciplina;
    private javax.swing.JLabel lblCodigoDisciplina;
    private javax.swing.JLabel lblNomeDisciplina;
    private javax.swing.JPanel pnlCodigoDisciplina;
    private javax.swing.JPanel pnlMainContainer;
    private javax.swing.JPanel pnlNomeDisciplina;
    private javax.swing.JPanel pnlRegisterContainer;
    private javax.swing.JTextField txtCodigoDisiciplina;
    private javax.swing.JTextField txtNomeDisciplina;
    // End of variables declaration                   
}
