/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.sava.conselho.view;

import br.com.ifba.sava.infrastructure.service.FacadeInstance;
import br.com.ifba.sava.infrastructure.view.HomeScreen;

/**
 *
 * @author marts
 */
public class CadastrarConselho extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarConselho
     */
    public CadastrarConselho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainContainer = new javax.swing.JPanel();
        pnlRegisterContainer = new javax.swing.JPanel();
        pnlCodigoAta = new javax.swing.JPanel();
        lblCodigoAta = new javax.swing.JLabel();
        txtCodigoAta = new javax.swing.JTextField();
        pnlAnoLetivo = new javax.swing.JPanel();
        lblAnoLetivo = new javax.swing.JLabel();
        txtAnoLetivo = new javax.swing.JTextField();
        btnCadastrarConselho = new javax.swing.JButton();
        pnlTrimestre = new javax.swing.JPanel();
        lblTrimestre = new javax.swing.JLabel();
        txtTrimestre = new javax.swing.JTextField();
        pnlCodigoConselho = new javax.swing.JPanel();
        lblCodigoConselho = new javax.swing.JLabel();
        txtCodigoConselho = new javax.swing.JTextField();
        btnVoltarConselho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainContainer.setBackground(new java.awt.Color(72, 71, 97));

        pnlRegisterContainer.setBackground(new java.awt.Color(218, 217, 237));

        pnlCodigoAta.setBackground(new java.awt.Color(102, 101, 120));

        lblCodigoAta.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblCodigoAta.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoAta.setText("Código Ata:");

        txtCodigoAta.setBackground(new java.awt.Color(102, 101, 120));
        txtCodigoAta.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtCodigoAta.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoAta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCodigoAta.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCodigoAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoAtaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCodigoAtaLayout = new javax.swing.GroupLayout(pnlCodigoAta);
        pnlCodigoAta.setLayout(pnlCodigoAtaLayout);
        pnlCodigoAtaLayout.setHorizontalGroup(
            pnlCodigoAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoAtaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigoAta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCodigoAta, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCodigoAtaLayout.setVerticalGroup(
            pnlCodigoAtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoAtaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCodigoAta)
                .addGap(11, 11, 11))
            .addComponent(txtCodigoAta)
        );

        pnlAnoLetivo.setBackground(new java.awt.Color(102, 101, 120));

        lblAnoLetivo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblAnoLetivo.setForeground(new java.awt.Color(255, 255, 255));
        lblAnoLetivo.setText("Ano Letivo:");

        txtAnoLetivo.setBackground(new java.awt.Color(102, 101, 120));
        txtAnoLetivo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtAnoLetivo.setForeground(new java.awt.Color(255, 255, 255));
        txtAnoLetivo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtAnoLetivo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAnoLetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoLetivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAnoLetivoLayout = new javax.swing.GroupLayout(pnlAnoLetivo);
        pnlAnoLetivo.setLayout(pnlAnoLetivoLayout);
        pnlAnoLetivoLayout.setHorizontalGroup(
            pnlAnoLetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnoLetivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnoLetivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnoLetivo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
        );
        pnlAnoLetivoLayout.setVerticalGroup(
            pnlAnoLetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnoLetivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAnoLetivo)
                .addGap(11, 11, 11))
            .addComponent(txtAnoLetivo)
        );

        btnCadastrarConselho.setBackground(new java.awt.Color(72, 71, 97));
        btnCadastrarConselho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarConselho.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarConselho.setText("Cadastrar Conselho");
        btnCadastrarConselho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarConselhoActionPerformed(evt);
            }
        });

        pnlTrimestre.setBackground(new java.awt.Color(102, 101, 120));

        lblTrimestre.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblTrimestre.setForeground(new java.awt.Color(255, 255, 255));
        lblTrimestre.setText("Trimestre:");

        txtTrimestre.setBackground(new java.awt.Color(102, 101, 120));
        txtTrimestre.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtTrimestre.setForeground(new java.awt.Color(255, 255, 255));
        txtTrimestre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtTrimestre.setCaretColor(new java.awt.Color(255, 255, 255));
        txtTrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrimestreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTrimestreLayout = new javax.swing.GroupLayout(pnlTrimestre);
        pnlTrimestre.setLayout(pnlTrimestreLayout);
        pnlTrimestreLayout.setHorizontalGroup(
            pnlTrimestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrimestreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrimestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTrimestre))
        );
        pnlTrimestreLayout.setVerticalGroup(
            pnlTrimestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrimestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtTrimestre, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(lblTrimestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCodigoConselho.setBackground(new java.awt.Color(102, 101, 120));

        lblCodigoConselho.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblCodigoConselho.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoConselho.setText("Código:");

        txtCodigoConselho.setBackground(new java.awt.Color(102, 101, 120));
        txtCodigoConselho.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtCodigoConselho.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoConselho.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCodigoConselho.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCodigoConselho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoConselhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCodigoConselhoLayout = new javax.swing.GroupLayout(pnlCodigoConselho);
        pnlCodigoConselho.setLayout(pnlCodigoConselhoLayout);
        pnlCodigoConselhoLayout.setHorizontalGroup(
            pnlCodigoConselhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoConselhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCodigoConselho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlCodigoConselhoLayout.setVerticalGroup(
            pnlCodigoConselhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodigoConselhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblCodigoConselho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCodigoConselho, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRegisterContainerLayout = new javax.swing.GroupLayout(pnlRegisterContainer);
        pnlRegisterContainer.setLayout(pnlRegisterContainerLayout);
        pnlRegisterContainerLayout.setHorizontalGroup(
            pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAnoLetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlTrimestre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlCodigoConselho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(pnlCodigoAta, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarConselho)
                .addGap(212, 212, 212))
        );
        pnlRegisterContainerLayout.setVerticalGroup(
            pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCodigoConselho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCodigoAta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlTrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlAnoLetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnCadastrarConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        btnVoltarConselho.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltarConselho.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnVoltarConselho.setText("voltar");
        btnVoltarConselho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarConselhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainContainerLayout = new javax.swing.GroupLayout(pnlMainContainer);
        pnlMainContainer.setLayout(pnlMainContainerLayout);
        pnlMainContainerLayout.setHorizontalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainerLayout.createSequentialGroup()
                .addGroup(pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainContainerLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(pnlRegisterContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainContainerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnVoltarConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        pnlMainContainerLayout.setVerticalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnVoltarConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(pnlRegisterContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoAtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAtaActionPerformed

    private void txtAnoLetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoLetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoLetivoActionPerformed

    private void btnCadastrarConselhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConselhoActionPerformed
        //Conselho conselho1 = new Conselho();
       
       //conselho1.setCodigoConselho(txtCodigoConselho.getText());
       //conselho1.setTrimestre(txtTrimestre.getText());
       //conselho1.setAnoLetivo(txtAnoLetivo.getText());
       //conselho1.setCodigoAta(txtCodigoAta.getText());
       
       //FacadeInstance.getInstance().saveConselho(conselho1);
    }//GEN-LAST:event_btnCadastrarConselhoActionPerformed

    private void txtTrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrimestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrimestreActionPerformed

    private void txtCodigoConselhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoConselhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoConselhoActionPerformed

    private void btnVoltarConselhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarConselhoActionPerformed
        this.dispose();
        HomeScreen tela1 = new HomeScreen();
        tela1.setVisible(true);
    }//GEN-LAST:event_btnVoltarConselhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarConselho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarConselho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarConselho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarConselho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarConselho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarConselho;
    private javax.swing.JButton btnVoltarConselho;
    private javax.swing.JLabel lblAnoLetivo;
    private javax.swing.JLabel lblCodigoAta;
    private javax.swing.JLabel lblCodigoConselho;
    private javax.swing.JLabel lblTrimestre;
    private javax.swing.JPanel pnlAnoLetivo;
    private javax.swing.JPanel pnlCodigoAta;
    private javax.swing.JPanel pnlCodigoConselho;
    private javax.swing.JPanel pnlMainContainer;
    private javax.swing.JPanel pnlRegisterContainer;
    private javax.swing.JPanel pnlTrimestre;
    private javax.swing.JTextField txtAnoLetivo;
    private javax.swing.JTextField txtCodigoAta;
    private javax.swing.JTextField txtCodigoConselho;
    private javax.swing.JTextField txtTrimestre;
    // End of variables declaration//GEN-END:variables
}
