/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.sava.itemavaliativo.view;

import br.com.ifba.sava.infrastructure.view.HomeScreen;

/**
 *
 * @author marts
 */
public class ItemAvaliativo extends javax.swing.JFrame {

    /**
     * Creates new form ItemAvaliativo
     */
    public ItemAvaliativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainContainer = new javax.swing.JPanel();
        pnlRegisterContainer = new javax.swing.JPanel();
        pnlDescricaoItem = new javax.swing.JPanel();
        lblDescricaoItem = new javax.swing.JLabel();
        txtDescricaoItem = new javax.swing.JTextField();
        btnCadastrarItem = new javax.swing.JButton();
        pnlNomeItem = new javax.swing.JPanel();
        lblNomeItem = new javax.swing.JLabel();
        txtNomeItem = new javax.swing.JTextField();
        btnVoltarItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainContainer.setBackground(new java.awt.Color(72, 71, 97));

        pnlRegisterContainer.setBackground(new java.awt.Color(218, 217, 237));

        pnlDescricaoItem.setBackground(new java.awt.Color(102, 101, 120));

        lblDescricaoItem.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblDescricaoItem.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricaoItem.setText("Descrição:");

        txtDescricaoItem.setBackground(new java.awt.Color(102, 101, 120));
        txtDescricaoItem.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtDescricaoItem.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricaoItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDescricaoItem.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDescricaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDescricaoItemLayout = new javax.swing.GroupLayout(pnlDescricaoItem);
        pnlDescricaoItem.setLayout(pnlDescricaoItemLayout);
        pnlDescricaoItemLayout.setHorizontalGroup(
            pnlDescricaoItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescricaoItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescricaoItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDescricaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDescricaoItemLayout.setVerticalGroup(
            pnlDescricaoItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescricaoItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDescricaoItem)
                .addGap(11, 11, 11))
            .addComponent(txtDescricaoItem)
        );

        btnCadastrarItem.setBackground(new java.awt.Color(72, 71, 97));
        btnCadastrarItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrarItem.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarItem.setText("Cadastrar Item");
        btnCadastrarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarItemActionPerformed(evt);
            }
        });

        pnlNomeItem.setBackground(new java.awt.Color(102, 101, 120));

        lblNomeItem.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblNomeItem.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeItem.setText("Nome:");

        txtNomeItem.setBackground(new java.awt.Color(102, 101, 120));
        txtNomeItem.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtNomeItem.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeItem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNomeItem.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNomeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNomeItemLayout = new javax.swing.GroupLayout(pnlNomeItem);
        pnlNomeItem.setLayout(pnlNomeItemLayout);
        pnlNomeItemLayout.setHorizontalGroup(
            pnlNomeItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlNomeItemLayout.setVerticalGroup(
            pnlNomeItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNomeItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNomeItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNomeItem, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRegisterContainerLayout = new javax.swing.GroupLayout(pnlRegisterContainer);
        pnlRegisterContainer.setLayout(pnlRegisterContainerLayout);
        pnlRegisterContainerLayout.setHorizontalGroup(
            pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(pnlNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(pnlDescricaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnCadastrarItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterContainerLayout.setVerticalGroup(
            pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDescricaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnCadastrarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        btnVoltarItem.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltarItem.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnVoltarItem.setText("voltar");
        btnVoltarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainContainerLayout = new javax.swing.GroupLayout(pnlMainContainer);
        pnlMainContainer.setLayout(pnlMainContainerLayout);
        pnlMainContainerLayout.setHorizontalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainerLayout.createSequentialGroup()
                .addGroup(pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainContainerLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(pnlRegisterContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainContainerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnVoltarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        pnlMainContainerLayout.setVerticalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnVoltarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(pnlRegisterContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescricaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoItemActionPerformed

    private void btnCadastrarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarItemActionPerformed

    }//GEN-LAST:event_btnCadastrarItemActionPerformed

    private void txtNomeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeItemActionPerformed

    private void btnVoltarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarItemActionPerformed
        this.dispose();
        HomeScreen tela1 = new HomeScreen();
        tela1.setVisible(true);
    }//GEN-LAST:event_btnVoltarItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemAvaliativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemAvaliativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemAvaliativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemAvaliativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemAvaliativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarItem;
    private javax.swing.JButton btnVoltarItem;
    private javax.swing.JLabel lblDescricaoItem;
    private javax.swing.JLabel lblNomeItem;
    private javax.swing.JPanel pnlDescricaoItem;
    private javax.swing.JPanel pnlMainContainer;
    private javax.swing.JPanel pnlNomeItem;
    private javax.swing.JPanel pnlRegisterContainer;
    private javax.swing.JTextField txtDescricaoItem;
    private javax.swing.JTextField txtNomeItem;
    // End of variables declaration//GEN-END:variables
}
