/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifba.sava.aluno.view;

/**
 *
 * @author sheor
 */
public class RegisterStudentScreen extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudentScreen
     */
    public RegisterStudentScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainContainer = new javax.swing.JPanel();
        pnlRegisterContainer = new javax.swing.JPanel();
        pnlName = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        pnlRegistrationNumber = new javax.swing.JPanel();
        lblRegistrationNumber = new javax.swing.JLabel();
        txtRegistrationNumber = new javax.swing.JTextField();
        pnlBirthYear = new javax.swing.JPanel();
        lblBirthYear = new javax.swing.JLabel();
        txtBirthYear = new javax.swing.JTextField();
        pnlCPF = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        pnlCity = new javax.swing.JPanel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        pnlCEP = new javax.swing.JPanel();
        lblCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        pnlNeighborhood = new javax.swing.JPanel();
        lblNeighborhood = new javax.swing.JLabel();
        txtNeighborhood = new javax.swing.JTextField();
        pnlStreet = new javax.swing.JPanel();
        lblStreet = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        pnNumber = new javax.swing.JPanel();
        lblNumber = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        pnlComplement = new javax.swing.JPanel();
        lblComplement = new javax.swing.JLabel();
        txtComplement = new javax.swing.JTextField();
        pnlUF = new javax.swing.JPanel();
        lblUF = new javax.swing.JLabel();
        txtUF = new javax.swing.JTextField();
        pnlDDD = new javax.swing.JPanel();
        lblDDD = new javax.swing.JLabel();
        txtDDD = new javax.swing.JTextField();
        pnlPhoneNumber = new javax.swing.JPanel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumbe = new javax.swing.JTextField();
        pnlEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainContainer.setBackground(new java.awt.Color(72, 71, 97));

        pnlRegisterContainer.setBackground(new java.awt.Color(218, 217, 237));

        pnlName.setBackground(new java.awt.Color(102, 101, 120));

        lblName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Nome:");

        txtName.setBackground(new java.awt.Color(102, 101, 120));
        txtName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNameLayout = new javax.swing.GroupLayout(pnlName);
        pnlName.setLayout(pnlNameLayout);
        pnlNameLayout.setHorizontalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNameLayout.setVerticalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        pnlRegistrationNumber.setBackground(new java.awt.Color(102, 101, 120));

        lblRegistrationNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblRegistrationNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrationNumber.setText("Matricula:");

        txtRegistrationNumber.setBackground(new java.awt.Color(102, 101, 120));
        txtRegistrationNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtRegistrationNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtRegistrationNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtRegistrationNumber.setCaretColor(new java.awt.Color(255, 255, 255));
        txtRegistrationNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrationNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrationNumberLayout = new javax.swing.GroupLayout(pnlRegistrationNumber);
        pnlRegistrationNumber.setLayout(pnlRegistrationNumberLayout);
        pnlRegistrationNumberLayout.setHorizontalGroup(
            pnlRegistrationNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrationNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlRegistrationNumberLayout.setVerticalGroup(
            pnlRegistrationNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrationNumberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrationNumber)
                .addGap(11, 11, 11))
            .addComponent(txtRegistrationNumber)
        );

        pnlBirthYear.setBackground(new java.awt.Color(102, 101, 120));

        lblBirthYear.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblBirthYear.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthYear.setText("Data de nasc.:");

        txtBirthYear.setBackground(new java.awt.Color(102, 101, 120));
        txtBirthYear.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtBirthYear.setForeground(new java.awt.Color(255, 255, 255));
        txtBirthYear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtBirthYear.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBirthYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBirthYearLayout = new javax.swing.GroupLayout(pnlBirthYear);
        pnlBirthYear.setLayout(pnlBirthYearLayout);
        pnlBirthYearLayout.setHorizontalGroup(
            pnlBirthYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBirthYearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBirthYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBirthYearLayout.setVerticalGroup(
            pnlBirthYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBirthYearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBirthYear)
                .addGap(11, 11, 11))
            .addComponent(txtBirthYear)
        );

        pnlCPF.setBackground(new java.awt.Color(102, 101, 120));

        lblCPF.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setText("CPF:");

        txtCPF.setBackground(new java.awt.Color(102, 101, 120));
        txtCPF.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtCPF.setForeground(new java.awt.Color(255, 255, 255));
        txtCPF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCPF.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCPFLayout = new javax.swing.GroupLayout(pnlCPF);
        pnlCPF.setLayout(pnlCPFLayout);
        pnlCPFLayout.setHorizontalGroup(
            pnlCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF)
                .addContainerGap())
        );
        pnlCPFLayout.setVerticalGroup(
            pnlCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCPF)
                .addGap(11, 11, 11))
            .addComponent(txtCPF)
        );

        pnlCity.setBackground(new java.awt.Color(102, 101, 120));

        lblCity.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("Cidade:");

        txtCity.setBackground(new java.awt.Color(102, 101, 120));
        txtCity.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtCity.setForeground(new java.awt.Color(255, 255, 255));
        txtCity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCity.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCityLayout = new javax.swing.GroupLayout(pnlCity);
        pnlCity.setLayout(pnlCityLayout);
        pnlCityLayout.setHorizontalGroup(
            pnlCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCityLayout.setVerticalGroup(
            pnlCityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCityLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCity)
                .addGap(11, 11, 11))
            .addComponent(txtCity)
        );

        pnlCEP.setBackground(new java.awt.Color(102, 101, 120));

        lblCEP.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblCEP.setForeground(new java.awt.Color(255, 255, 255));
        lblCEP.setText("CEP:");

        txtCEP.setBackground(new java.awt.Color(102, 101, 120));
        txtCEP.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtCEP.setForeground(new java.awt.Color(255, 255, 255));
        txtCEP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCEP.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCEPLayout = new javax.swing.GroupLayout(pnlCEP);
        pnlCEP.setLayout(pnlCEPLayout);
        pnlCEPLayout.setHorizontalGroup(
            pnlCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCEPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCEP)
                .addContainerGap())
        );
        pnlCEPLayout.setVerticalGroup(
            pnlCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCEPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCEP)
                .addGap(11, 11, 11))
            .addComponent(txtCEP)
        );

        pnlNeighborhood.setBackground(new java.awt.Color(102, 101, 120));

        lblNeighborhood.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblNeighborhood.setForeground(new java.awt.Color(255, 255, 255));
        lblNeighborhood.setText("Bairro:");

        txtNeighborhood.setBackground(new java.awt.Color(102, 101, 120));
        txtNeighborhood.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtNeighborhood.setForeground(new java.awt.Color(255, 255, 255));
        txtNeighborhood.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNeighborhood.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNeighborhood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNeighborhoodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNeighborhoodLayout = new javax.swing.GroupLayout(pnlNeighborhood);
        pnlNeighborhood.setLayout(pnlNeighborhoodLayout);
        pnlNeighborhoodLayout.setHorizontalGroup(
            pnlNeighborhoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNeighborhoodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNeighborhood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNeighborhood)
                .addContainerGap())
        );
        pnlNeighborhoodLayout.setVerticalGroup(
            pnlNeighborhoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNeighborhoodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNeighborhood)
                .addGap(11, 11, 11))
            .addComponent(txtNeighborhood)
        );

        pnlStreet.setBackground(new java.awt.Color(102, 101, 120));

        lblStreet.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblStreet.setForeground(new java.awt.Color(255, 255, 255));
        lblStreet.setText("Rua:");

        txtStreet.setBackground(new java.awt.Color(102, 101, 120));
        txtStreet.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtStreet.setForeground(new java.awt.Color(255, 255, 255));
        txtStreet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtStreet.setCaretColor(new java.awt.Color(255, 255, 255));
        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStreetLayout = new javax.swing.GroupLayout(pnlStreet);
        pnlStreet.setLayout(pnlStreetLayout);
        pnlStreetLayout.setHorizontalGroup(
            pnlStreetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStreetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStreet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStreet)
                .addContainerGap())
        );
        pnlStreetLayout.setVerticalGroup(
            pnlStreetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStreetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStreet)
                .addGap(11, 11, 11))
            .addComponent(txtStreet)
        );

        pnNumber.setBackground(new java.awt.Color(102, 101, 120));

        lblNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblNumber.setText("Nº");

        txtNumber.setBackground(new java.awt.Color(102, 101, 120));
        txtNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNumber.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNumberLayout = new javax.swing.GroupLayout(pnNumber);
        pnNumber.setLayout(pnNumberLayout);
        pnNumberLayout.setHorizontalGroup(
            pnNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNumberLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );
        pnNumberLayout.setVerticalGroup(
            pnNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(lblNumber))
        );

        pnlComplement.setBackground(new java.awt.Color(102, 101, 120));

        lblComplement.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblComplement.setForeground(new java.awt.Color(255, 255, 255));
        lblComplement.setText("Complemento:");

        txtComplement.setBackground(new java.awt.Color(102, 101, 120));
        txtComplement.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtComplement.setForeground(new java.awt.Color(255, 255, 255));
        txtComplement.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtComplement.setCaretColor(new java.awt.Color(255, 255, 255));
        txtComplement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlComplementLayout = new javax.swing.GroupLayout(pnlComplement);
        pnlComplement.setLayout(pnlComplementLayout);
        pnlComplementLayout.setHorizontalGroup(
            pnlComplementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblComplement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplement, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlComplementLayout.setVerticalGroup(
            pnlComplementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComplementLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblComplement)
                .addGap(11, 11, 11))
            .addComponent(txtComplement)
        );

        pnlUF.setBackground(new java.awt.Color(102, 101, 120));

        lblUF.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblUF.setForeground(new java.awt.Color(255, 255, 255));
        lblUF.setText("UF:");

        txtUF.setBackground(new java.awt.Color(102, 101, 120));
        txtUF.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtUF.setForeground(new java.awt.Color(255, 255, 255));
        txtUF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUF.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUFLayout = new javax.swing.GroupLayout(pnlUF);
        pnlUF.setLayout(pnlUFLayout);
        pnlUFLayout.setHorizontalGroup(
            pnlUFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUF)
                .addContainerGap())
        );
        pnlUFLayout.setVerticalGroup(
            pnlUFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUF)
                .addGap(11, 11, 11))
            .addComponent(txtUF)
        );

        pnlDDD.setBackground(new java.awt.Color(102, 101, 120));

        lblDDD.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblDDD.setForeground(new java.awt.Color(255, 255, 255));
        lblDDD.setText("DDD:");

        txtDDD.setBackground(new java.awt.Color(102, 101, 120));
        txtDDD.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtDDD.setForeground(new java.awt.Color(255, 255, 255));
        txtDDD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDDD.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDDDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDDDLayout = new javax.swing.GroupLayout(pnlDDD);
        pnlDDD.setLayout(pnlDDDLayout);
        pnlDDDLayout.setHorizontalGroup(
            pnlDDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDDDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDDD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDDD))
        );
        pnlDDDLayout.setVerticalGroup(
            pnlDDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDDDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDDD)
                .addGap(11, 11, 11))
            .addComponent(txtDDD)
        );

        pnlPhoneNumber.setBackground(new java.awt.Color(102, 101, 120));

        lblPhoneNumber.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setText("Telefone:");

        txtPhoneNumbe.setBackground(new java.awt.Color(102, 101, 120));
        txtPhoneNumbe.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtPhoneNumbe.setForeground(new java.awt.Color(255, 255, 255));
        txtPhoneNumbe.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPhoneNumbe.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPhoneNumbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumbeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPhoneNumberLayout = new javax.swing.GroupLayout(pnlPhoneNumber);
        pnlPhoneNumber.setLayout(pnlPhoneNumberLayout);
        pnlPhoneNumberLayout.setHorizontalGroup(
            pnlPhoneNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhoneNumbe, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );
        pnlPhoneNumberLayout.setVerticalGroup(
            pnlPhoneNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneNumberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPhoneNumber)
                .addGap(11, 11, 11))
            .addComponent(txtPhoneNumbe)
        );

        pnlEmail.setBackground(new java.awt.Color(102, 101, 120));

        lblEmail.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");

        txtEmail.setBackground(new java.awt.Color(102, 101, 120));
        txtEmail.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmail)
                .addGap(11, 11, 11))
            .addComponent(txtEmail)
        );

        btnRegister.setBackground(new java.awt.Color(72, 71, 97));
        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(72, 71, 97));
        btnRegister.setText("Cadastrar Aluno");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterContainerLayout = new javax.swing.GroupLayout(pnlRegisterContainer);
        pnlRegisterContainer.setLayout(pnlRegisterContainerLayout);
        pnlRegisterContainerLayout.setHorizontalGroup(
            pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRegistrationNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlCEP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNeighborhood, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBirthYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                        .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                                .addComponent(pnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterContainerLayout.createSequentialGroup()
                                .addGap(0, 125, Short.MAX_VALUE)
                                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pnlUF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlDDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pnlComplement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(118, 118, 118))
                    .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlRegisterContainerLayout.setVerticalGroup(
            pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlComplement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                        .addComponent(pnlCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterContainerLayout.createSequentialGroup()
                        .addComponent(pnlPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(pnlCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout pnlMainContainerLayout = new javax.swing.GroupLayout(pnlMainContainer);
        pnlMainContainer.setLayout(pnlMainContainerLayout);
        pnlMainContainerLayout.setHorizontalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContainerLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(pnlRegisterContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        pnlMainContainerLayout.setVerticalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainContainerLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(pnlRegisterContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtRegistrationNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrationNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrationNumberActionPerformed

    private void txtBirthYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthYearActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtNeighborhoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNeighborhoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNeighborhoodActionPerformed

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void txtComplementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUFActionPerformed

    private void txtDDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDDDActionPerformed

    private void txtPhoneNumbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumbeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumbeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudentScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblBirthYear;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblComplement;
    private javax.swing.JLabel lblDDD;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNeighborhood;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblRegistrationNumber;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblUF;
    private javax.swing.JPanel pnNumber;
    private javax.swing.JPanel pnlBirthYear;
    private javax.swing.JPanel pnlCEP;
    private javax.swing.JPanel pnlCPF;
    private javax.swing.JPanel pnlCity;
    private javax.swing.JPanel pnlComplement;
    private javax.swing.JPanel pnlDDD;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlMainContainer;
    private javax.swing.JPanel pnlName;
    private javax.swing.JPanel pnlNeighborhood;
    private javax.swing.JPanel pnlPhoneNumber;
    private javax.swing.JPanel pnlRegisterContainer;
    private javax.swing.JPanel pnlRegistrationNumber;
    private javax.swing.JPanel pnlStreet;
    private javax.swing.JPanel pnlUF;
    private javax.swing.JTextField txtBirthYear;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtComplement;
    private javax.swing.JTextField txtDDD;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNeighborhood;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPhoneNumbe;
    private javax.swing.JTextField txtRegistrationNumber;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables
}
